name: Build & Deploy to VM

on:
  push:
    branches: [ your_branch_name ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/mywebapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-tag: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Set image tag
        id: set-tag
        run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.TAG }}

  deploy:
    needs: build-and-deploy
    runs-on: vmware
    steps:
      - name: Deploy on VM
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ needs.build-and-deploy.outputs.image-tag }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.WEB_VM_SSH_KEY }}
          password: ${{ secrets.WEB_VM_PASSWORD }}
          script: |
            cd /home/ubuntu/app
            export IMAGE_NAME=${{ env.IMAGE_NAME }}
            export IMAGE_TAG=${{ env.IMAGE_TAG }}
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}
            docker compose pull
            docker compose up -d